name: Generate release-artifacts

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.6

      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o blueiris_exporter-amd64-linux -tags LINUX
      
      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -o blueiris_exporter-amd64.exe
      
      - name: Upload Artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            blueiris_exporter-amd64-linux
            blueiris_exporter-amd64.exe