name: Generate release-artifacts

# on events
on:
  release:
    types: 
      - created

# workflow tasks
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.6

      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o bin/blueiris_exporter-amd64-linux
      
      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -o bin/blueiris_exporter-amd64.exe
      
      - name: Upload Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          asset_path: bin
          upload_url: ${{ github.event.release.upload_url }}